name: Deploy Spring Boot to Azure Spring Apps

on:
  push:
    branches:
      - main  # Esegui il deploy quando c'è un push sul branch principale
  workflow_dispatch:  # Permette di avviare manualmente la pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Usa Temurin per JDK
          java-version: '17'

      # Step 3: Build dell'app Spring Boot
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 4: Login ad Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 5: Deploy su Azure Spring Apps
      - name: Deploy to Azure Spring Apps
        run: |
          az spring app deploy --name mvvm \
            --service mvvm \
            --resource-group test \
            --artifact-path target/*.jar
